name: EnferChat
version: 1.0.0
main: fr.ravguillaume.enferchat.EnferChatPlugin
api-version: 1.20
description: Plugin de chat avec intégration du système de niveaux
author: Saguime
soft-depend:
  - Niveaux
